[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore anything with the word funkymonkey anywhere in the path
    '''infra''',
    '''config'''
  ]

  # Ignore based on any subset of the line
  regexes = [
  ]