apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-values
  namespace: infra
data:
  gitlab-values.yaml: |
    # External URL for accessing GitLab
    external_url: 'http://gitlab-infra.apps.itz-j3yfm1.hub04-lb.techzone.ibm.com'

    # Nginx settings
    external_url_gitlab: '@gitlab-url@'
    webhook: '@webhook-url@'

    nginx:
      enable: true
      redirect_http_to_https: false
      listen_https: false

    # GitLab webservice settings
    gitlab_rails:
      webservice_external_port: 80
      db_adapter: postgresql
      db_host: gitlab-postgresql
      db_port: 5432
      db_username: gitlab
      db_password: gitlab
      db_database: gitlab
      security_context:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

    # Gitaly settings for persistence
    gitaly:
      persistence: true
      storage_class: 'standard'
      security_context:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

    # GitLab Shell settings
    gitlab_shell:
      enabled: false
      service:
        externalPort: 0
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

    # Redis settings
    redis:
      enable: true
      master:
        enable: true
      replica:
        enable: false

    # PostgreSQL settings
    postgresql:
      enable: false  # Using external DB

    # Prometheus settings
    prometheus:
      enable: false

    # Registry settings
    registry:
      enable: false
