apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-values
data:
  values.yaml: |
    global:
      hosts:
        domain: apps-crc.testing
        gitlab:
          name: @HOSTNAME
        https: false
      ingress:
        tls:
          enabled: false
      edition: ce
      nginx:
        redirectHttpToHttps: false

    gitlab:
      enabled: true
      migrations:
        initialRootPassword: {}
      webservice:
        externalPort: 80
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      gitaly:
        persistence:
          storageClass: standard  # adjust to your PVC setup
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      gitlab-shell:
        service:
          externalPort: 22
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000

    redis:
      install: true
      master:
        install: true
      replica:
        install: false

    postgresql:
      install: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

    nginx-ingress:
      controller:
        enabled: false

    prometheus:
      install: false

    registry:
      enabled: false
