global:
  hosts:
    domain: apps-crc.testing
    gitlab:
      name: null           # GitLab will use a generated name like gitlab.example.local
    https: false           # Keep false unless you have TLS
  edition: ce

# Use built-in PostgreSQL and Redis
postgresql:
  install: true

redis:
  install: true
  master:
    install: true
  replica:
    install: false

nginx-ingress:
  controller:
    enabled: true
    ingressClass: nginx

prometheus:
  install: false

gitlab:
  enabled: true
  migrations:
    initialRootPassword: {}

registry:
  enabled: false
