apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uat-spring-petclinic
spec:
  destination:
    namespace: uat
    server: https://kubernetes.default.svc
  project: spring-petclinic
  source:
    path: environments/uat
    repoURL: https://github.com/rrahhal1/spring-petclinic-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
