apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-spring-petclinic
spec:
  destination:
    namespace: demo-prod
    server: https://kubernetes.default.svc
  project: spring-petclinic
  source:
    path: environments/prod
    repoURL: https://github.com/siamaksade/spring-petclinic-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true